### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by ralonsokichink** [itsfaraaz/Lakefield-Library#1] opened 2020-03-18 06:00 UTC
I tried to login and i get User successfully signed into the system but i cant go throught account info

**Comment by itsfaraaz** [comment] 2020-03-18 15:56
Hi, what do you mean account info? Can you post a screenshot? Thanks

**Comment by vesvello** [comment] 2020-03-19 02:46
after login come back to home screen

<img width="800" alt="Captura de Pantalla 2020-03-18 a la(s) 20 44 02" src="https://user-images.githubusercontent.com/278606/77026496-65d9cd80-6959-11ea-9a0d-ae293e1bb356.png">

<img width="828" alt="Captura de Pantalla 2020-03-18 a la(s) 20 44 16" src="https://user-images.githubusercontent.com/278606/77026525-77bb7080-6959-11ea-8a0d-f3137863d18e.png">

**Comment by itsfaraaz** [comment] 2020-03-24 20:03
Hey, for some reason the code for transitioning the controllers was not there. The issue is now fixed.

**Closed by itsfaraaz** 2020-03-24 20:03 UTC
Labels: bug
